# Generated by Django 3.2.4 on 2022-12-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('Unit', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('EmployeeAddress', models.CharField(max_length=500)),
                ('EmployeeDOB', models.DateField()),
                ('EmployeSSN', models.CharField(max_length=500)),
                ('EmployeeRank', models.CharField(max_length=500)),
                ('EmployeeHeight', models.CharField(max_length=500)),
                ('EmployeeWeight', models.CharField(max_length=500)),
                ('EmployeeRace', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('LogId', models.AutoField(primary_key=True, serialize=False)),
                ('MadeBy', models.CharField(max_length=500)),
                ('Code', models.CharField(max_length=500)),
                ('Type', models.CharField(max_length=500)),
                ('DateOccured', models.DateField()),
                ('Location', models.CharField(max_length=500)),
                ('Time', models.CharField(max_length=500)),
                ('Evidence', models.CharField(max_length=500)),
                ('Parties', models.CharField(max_length=500)),
                ('Action', models.CharField(max_length=500)),
                ('Notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('UnitId', models.AutoField(primary_key=True, serialize=False)),
                ('UnitName', models.CharField(max_length=500)),
                ('UnitType', models.CharField(max_length=500)),
                ('UnitChief', models.CharField(max_length=500)),
                ('UnitCreationDate', models.DateField()),
                ('UnitStatus', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('VehicleId', models.AutoField(primary_key=True, serialize=False)),
                ('PlateNumber', models.CharField(max_length=500)),
                ('Make', models.CharField(max_length=500)),
                ('Model', models.CharField(max_length=500)),
                ('Year', models.CharField(max_length=500)),
                ('DatePurchased', models.DateField()),
                ('Assignment', models.CharField(max_length=500)),
            ],
        ),
    ]
